title = "My New Hugo Site"
baseURL = "https://qetr1ck-op.github.io/blog"
languageCode = "en-US"

theme = "hugo-code-editor-theme"
relativeURLs = true

[Params]
  Author = "Orest Prystayko"
  locale = "en-US"
  disqusShortname = "qetr1ck-op"